mydata = [
    {
        "name" : "Germany",
        "town" : "Germany - Berlin",
        "Entry": "Restricted Entry if you are visiting from a high risk area or if you are coming from outside of europe. High risk areas are updated each day depending on current case numbers. If you are coming from such an area you have to quarantine and follow the reporting requirements.",
        "Hygiene": "Masks are necessary in stores, on shopping streets, during travelling per public transports, cinemas, museums, theaters and similar places. The minimum social distance is 1.5 metres to people from other households. ",
        "Activity": "Many activities are allowed with limited access or additional regulations. From the start of november many places like hotels will be closed for respectively some weeks.",
        "Departure": "For your departure the hygiene regulations for public transports have to be followed.",
        "HygieneDep": "Masks are necessary during shopping, travelling per public transports and in public transport areas (e.g. train station). ",
        "Other": "As the current 7-day-inzidenz is over 210,4 per 100.000 residents (which is over the treshold 50) the regulations have to be tightened (28.Oct, 2020).",
        "Links": "berlin.de/corona/en/",
        "Dates": "29.Oct, 2020",
        "https":"y"
    },
    {
        "name" : "Germany",
        "town" : "Germany - Dresden",
        "Entry": "Restricted Entry if you are visiting from a high risk area or if you are coming from outside of europe. High risks areas are updated each day depending on current case numbers. If you are coming from such an area you have to quarantine and follow the reporting requirements. All people coming from such an area  must present themselves for a SARS-CoV-2 coronavirus test within ten days. If you are coming from a non-risk-area such measures are not required.",
        "Hygiene": "The minimum social distance is 1.5 metres to people from other households. Mouth-and-nose coverings in enclosed spaces are necessary, examples are: doctors offices, buildings with public access like shopping centers, schools, churches, public transport, shops and buisnesses. Outdoors mouth-and-nose coverings are required at local public transport stops, in railway stations and in highly frequented city centre area.  ",
        "Activity": "Many activities are allowed with limited access or additional regulations. From the start of november many places like hotels will be closed for respectively some weeks.",
        "Departure": "For your departure the hygiene regulations for public transports have to be followed.",
        "HygieneDep": "The minimum social distance is 1.5 metres to people from other households. Mouth-and-nose coverings in enclosed spaces are necessary, examples are: buildings with public access like shopping centers, public transport, shops and buisnesses. Outdoors mouth-and-nose coverings are required at local public transport stops, in railway stations and in highly frequented city centre area. ",
        "Other": "As the current 7-day-inzidenz is  104 (which is over 50 per 100.000 residents) the regulations have to be tightened (28.Oct, 2020).",
        "Links": "dresden.de/en/city/corona_en.php",
        "Dates": "16.Nov, 2020",
        "https":"y"
    },
    {
        "name" : "Portugal",
        "town" : "Portugal - A\xE7ores Island", 
        "Entry": "You must present, at the time of arrival, a proof of laboratory test for screening for infection by SARS-CoV-2 with a negative result.", 
        "Hygiene": "Masks are necessary in closed public spaces and travelling per public transports. Required 2 meters distancing at all times. The Clean&Safe seal allows the identification of establishments and services that have implemented reinforced hygiene and safety measures.",
        "Activity": "Many activities are allowed with sometimes limited access.", 
        "Departure": "Obligatory 2m social distancing and wearing a mask at all times. If it is a returning flight, you must present a negative test for SARS-CoV-2 at the time of arrival. Passengers who have not taken a PCR test will do so at the respective airport upon arrival.",
        "HygieneDep": "Masks are necessary in closed public spaces and travelling per public transports. Required 2 meters distancing at all times. ",
        "Other": "Flying to and from Portugal is allowed to countries that integrate the European Union; Associated countries of the Schengen Area, United Kingdom, Australia, Canada, China, Georgia, Japan, Morocco, New Zealand, Rwanda, Thailand, Tunisia, Uruguay and South Korea.",
        "Links": "visitmadeira.pt/en-gb/homepage?AreaId=16",
        "Dates": "16.Nov, 2020",
        "https":"n"
    },
    {
        "name" : "Portugal", 
        "town" : "Portugal - Continental", 
        "Entry": "If you are visiting from a high risk country you must present, at the time of departure from these countries, a proof of laboratory test for screening for infection by SARS-CoV-2 with a negative result.", 
        "Hygiene": "Masks are obligatory in public. Required 2 meters distancing at all times. The Clean&Safe seal allows the identification of establishments and services that have implemented reinforced hygiene and safety measures.",
        "Activity": "Forbidden activities with more than 5 people. Public spaces must close before 1am and alcoholic beverages are forbidden after 8pm. Bars and discos must remain closed.",  
        "Departure": "When arriving to the airport, body temperature screening is performed to all passengers. Obligatory 2m social distancing and wearing a mask at all times.",
        "HygieneDep": "Masks are obligatory in public. Required 2 meters distancing at all times. ",
        "Other": "Flying to and from Portugal is allowed to countries that integrate the European Union; Associated countries of the Schengen Area, United Kingdom, Australia, Canada, China, Georgia, Japan, Morocco, New Zealand, Rwanda, Thailand, Tunisia, Uruguay and South Korea.",
        "Links": "covid19.min-saude.pt/#",
        "Dates": "24.Oct, 2020",
        "https":"y"
    },
    {
        "name" : "Portugal",
        "town" : "Portugal - Madeira Island", 
        "Entry": "You must present, at the time of arrival, a proof of laboratory test for screening for infection by SARS-CoV-2 with a negative result.", 
        "Hygiene": "Masks are obligatory at all times. The Clean&Safe seal allows the identification of establishments and services that have implemented reinforced hygiene and safety measures.There is no quarantine requirement for travellers to Sweden.",
        "Activity": "Many activities are allowed with sometimes limited access.",
        "Departure": "Obligatory 2m social distancing and wearing a mask at all times. If it is a returning flight, you must present a negative test for SARS-CoV-2 at the time of arrival. Passengers who have not taken a PCR test will do so at the respective airport upon arrival.",
        "HygieneDep": "Masks are obligatory at all times.",
        "Other": "Flying to and from Portugal is allowed to countries that integrate the European Union; Associated countries of the Schengen Area, United Kingdom, Australia, Canada, China, Georgia, Japan, Morocco, New Zealand, Rwanda, Thailand, Tunisia, Uruguay and South Korea.",
        "Links":"visitmadeira.pt/en-gb/homepage?AreaId=16",
        "Dates": "20.Oct, 2020",
        "https":"n"
    },
    {
        "name" : "Sweden",
        "town" : "Sweden - Stockholm", 
        "Entry": "There is an entry ban until December 22 for non-essential travel to Sweden from countries outside the EU. The entry ban does not apply to citizens of EU/EEA countries, UK, Switzerland, Andorra, Monaco, San Marino and the Vatican, or their families, or for travels to Sweden from the EU/EEA area. Furthermore, the ban does not apply if you or a close relative already live here as a permanent resident or hold a residence permit in Sweden or another EU country, or if you have a national visa to Sweden. You do not need the coronavirus test",
        "Hygiene": "There is no general requirement to wear a face mask in normal social situations, in public places, in public transport etc.",
        "Activity": "Public gatherings and events may have a maximum of 50 participants. The Swedish Government has decided that restaurants and cafes shall be exempt from the 50-person limit. The change applies from 8 October 2020.",
        "Departure": "Please pay close attention to the information given by your airline. Many airline companies require you to wear a face mask on board.",
        "HygieneDep": "Masks are not necessary during shopping and travelling per public transports.",
        "Other": "In Sweden, anyone with symptoms can get a PCR test which will determine if there is an active Covid-19 infection. If you are interested in doing a PCR test, contact phone number 1177.  ",
        "Links": "www.krisinformation.se/en/hazards-and-risks/disasters-and-incidents/2020/official-information-on-the-new-coronavirus/visiting-sweden-during-the-covid-19-pandemic",
        "Dates": "29.Oct, 2020",
        "https":"n"
    }
];
